#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXpresent
Version  : 1.0.0
Release  : 5
URL      : https://www.x.org/releases/individual/lib/libXpresent-1.0.0.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXpresent-1.0.0.tar.gz
Summary  : X Present  Library
Group    : Development/Tools
License  : HPND
Requires: libXpresent-lib
Requires: libXpresent-doc
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXrandr-dev
BuildRequires : pkgconfig(presentproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
This package contains header files and documentation for the Present
extension.  Library and server implementations are separate.

%package dev
Summary: dev components for the libXpresent package.
Group: Development
Requires: libXpresent-lib
Provides: libXpresent-devel

%description dev
dev components for the libXpresent package.


%package doc
Summary: doc components for the libXpresent package.
Group: Documentation

%description doc
doc components for the libXpresent package.


%package lib
Summary: lib components for the libXpresent package.
Group: Libraries

%description lib
lib components for the libXpresent package.


%prep
%setup -q -n libXpresent-1.0.0

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xpresent.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
